declare module '*.css'
declare module '*.svg'
declare module 'header/Header'
declare module 'footer/Footer'
declare module 'state/GlobalState'
declare module 'state/Atoms'
declare module 'state/Selectors'